#!/usr/bin/env bash
#
# Regenerate docs/design/screenshots/ from the code on this commit.
#
# ── What this does, and why every step is here ────────────────────────────────
#
# A screenshot is only worth committing if it can be re-taken. This starts a real
# Postgres, migrates and seeds it, serves the API, builds and serves the dashboard,
# drives a real Chrome over the DevTools Protocol, and shuts all of it down again.
#
# ── Trap 1 · `pg-up.sh` exports DB_DATABASE ──────────────────────────────────
#
# `pg-up.sh` EXPORTS `DB_DATABASE`, defaulting to `rafeeq_test` — and an exported
# variable beats `.env`, because Laravel's Dotenv does not overwrite what is already
# in the environment. So the first version of this script ran `migrate:fresh`
# over the TEST database while believing it was working on its own copy.
#
# Naming the database BEFORE sourcing `pg-up.sh` is what fixes it: that script honours
# a pre-set `DB_DATABASE`.
#
# ── Trap 2 · `artisan serve` DELETES the environment ─────────────────────────
#
# Exporting `DB_DATABASE` is still not enough, and this one is genuinely surprising.
# `artisan serve` runs the application in a CHILD `php -S` process, and it maps every
# environment variable that is NOT on a short allowlist to `false`
# (`ServeCommand::$passthroughVariables`, and `[$key => false]` at ServeCommand.php:188).
# Symfony's Process treats `false` as "unset this", so the child starts WITHOUT the
# exports and re-reads an env file from disk. That is deliberate — it is how editing
# `.env` is picked up on reload — and it meant the console commands here talked to
# `rafeeq_demo` while the served API talked to `rafeeq`, which does not exist:
#
#     FATAL: database "rafeeq" does not exist
#
# `APP_ENV` *is* on that allowlist. So naming an ENVIRONMENT, rather than passing
# individual variables, is the one lever that steers the console and the served app
# together: both then load `backend/.env.demo`.
#
# That is also why this no longer edits `backend/.env`, which is what an earlier
# version did — a mutation it could leave behind if it died halfway.
#
# Usage:
#   ./scripts/screenshots.sh
#
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
RUN_DIR="${TMPDIR:-/tmp}/rafeeq-screenshots"
CHROME="${CHROME:-/opt/playwright/chromium-1232/chrome-linux64/chrome}"

API_PORT=8000
WEB_PORT=3000
CDP_PORT=9222

# Defined once, then used BOTH for the exports below and for the generated env file,
# so the console and the served app cannot drift apart.
DEMO_DB=rafeeq_demo
DEMO_DB_USER="$(whoami)"
# Forced by Laravel: the env file name is derived from APP_ENV, which must be `local`.
ENV_FILE="$REPO_ROOT/backend/.env.local"
ENV_MARKER="# generated by scripts/screenshots.sh — safe to delete"

# For `pg-up.sh` (which creates the database) and for the artisan CONSOLE commands.
# Named before pg-up.sh can default it to the test database — trap 1 above.
export DB_DATABASE="$DEMO_DB"
export DB_USERNAME="$DEMO_DB_USER"
export DB_PASSWORD=""

# The lever that survives into the served child — trap 2 above.
#
# It has to be `local` specifically, not a name of our choosing like `demo`:
# `InfrastructureServiceProvider` refuses the `log` SMS driver outside local/testing
# (ServeCommand.php aside, see InfrastructureServiceProvider.php:34), because a `log`
# driver in a real environment means OTPs are silently discarded. Admin login resolves
# `SmsGateway`, so under APP_ENV=demo the login request died with that very guard —
# correctly. And `http`/`whatsapp_cloud` cannot work here: there are no credentials and
# no outbound network. So: `local`.
export APP_ENV=local

# Screenshot-only, never a real credential. Long enough for the seeders' own floors.
export SEED_ADMIN_EMAIL="admin@rafeeq.local"
export SEED_ADMIN_PHONE="0790000000"
export SEED_ADMIN_NAME="مدير رفيق"
export SEED_ADMIN_PASSWORD="screenshots-only-not-a-secret"
export DEMO_SEED_PASSWORD="screenshots-only-not-a-secret"

mkdir -p "$RUN_DIR"
PIDS=()
cleanup() { for pid in "${PIDS[@]:-}"; do kill "$pid" 2>/dev/null || true; done; }
trap cleanup EXIT

wait_for() { # url, label, logfile
  for _ in $(seq 1 45); do
    if [[ "$(curl -s -o /dev/null -w '%{http_code}' "$1")" == "200" ]]; then
      echo "==> $2 ready"; return 0
    fi
    sleep 2
  done
  # Without this the only output was "api never came up", which says nothing about
  # why. The log is the whole diagnosis and it is already being written.
  echo "!! $2 never came up: $1" >&2
  if [[ -n "${3:-}" && -f "$3" ]]; then
    echo "---- last 40 lines of $3 ----" >&2
    tail -40 "$3" >&2
  fi
  return 1
}

# ── 0 · the environment file both processes will read ────────────────────────
# Built from `.env.example`, not from `.env`: it must not copy real secrets, and it
# has to work on a fresh clone where `.env` may not exist yet. `.env.*` is already
# gitignored (root .gitignore line 9), so this file never enters a commit.
#
# `.env.local` is a name a developer may well be using for their own settings, and the
# filename is not ours to choose (see APP_ENV above). So refuse rather than overwrite:
# losing someone's local configuration to a docs script would be a poor trade.
if [[ -f "$ENV_FILE" ]] && ! head -1 "$ENV_FILE" | grep -qF "$ENV_MARKER"; then
  {
    echo "!! $ENV_FILE already exists and was not written by this script."
    echo "   This script needs APP_ENV=local, and Laravel derives the env file name from"
    echo "   APP_ENV, so it cannot pick a different one. Move your file aside and re-run."
  } >&2
  exit 1
fi

echo "==> writing backend/.env.local"
{
echo "$ENV_MARKER"
sed -E \
  -e "s|^APP_ENV=.*|APP_ENV=local|" \
  -e "s|^APP_KEY=.*|APP_KEY=base64:$(head -c 32 /dev/urandom | base64)|" \
  -e "s|^APP_URL=.*|APP_URL=http://127.0.0.1:$API_PORT|" \
  -e "s|^DB_DATABASE=.*|DB_DATABASE=$DEMO_DB|" \
  -e "s|^DB_USERNAME=.*|DB_USERNAME=$DEMO_DB_USER|" \
  -e "s|^DB_PASSWORD=.*|DB_PASSWORD=|" \
  -e "s|^CACHE_STORE=.*|CACHE_STORE=file|" \
  -e "s|^QUEUE_CONNECTION=.*|QUEUE_CONNECTION=sync|" \
  -e "s|^SESSION_DRIVER=.*|SESSION_DRIVER=file|" \
  -e "s|^SEED_ADMIN_EMAIL=.*|SEED_ADMIN_EMAIL=$SEED_ADMIN_EMAIL|" \
  -e "s|^SEED_ADMIN_PHONE=.*|SEED_ADMIN_PHONE=$SEED_ADMIN_PHONE|" \
  -e "s|^SEED_ADMIN_NAME=.*|SEED_ADMIN_NAME=\"$SEED_ADMIN_NAME\"|" \
  -e "s|^SEED_ADMIN_PASSWORD=.*|SEED_ADMIN_PASSWORD=$SEED_ADMIN_PASSWORD|" \
  -e "s|^DEMO_SEED_PASSWORD=.*|DEMO_SEED_PASSWORD=$DEMO_SEED_PASSWORD|" \
  -e "s|^SMS_DRIVER=.*|SMS_DRIVER=log|" \
  -e "s|^SMS_FALLBACK=.*|SMS_FALLBACK=|" \
  "$REPO_ROOT/backend/.env.example"
} > "$ENV_FILE"

# ── 1 · database ─────────────────────────────────────────────────────────────
# shellcheck source=./pg-up.sh
. "$REPO_ROOT/scripts/pg-up.sh"

cd "$REPO_ROOT/backend"
echo "==> migrating + seeding $DEMO_DB"
php artisan migrate:fresh --force --seed >/dev/null
php artisan db:seed --class=DemoSeeder --force >/dev/null

# ── 2 · api ──────────────────────────────────────────────────────────────────
php artisan serve --host=127.0.0.1 --port="$API_PORT" >"$RUN_DIR/api.log" 2>&1 &
PIDS+=($!)
wait_for "http://127.0.0.1:$API_PORT/api/v1/config" "api" "$RUN_DIR/api.log"

# ── 3 · dashboard ────────────────────────────────────────────────────────────
cd "$REPO_ROOT/frontend/admin-dashboard"
export NEXT_PUBLIC_API_URL="http://127.0.0.1:$API_PORT"
echo "NEXT_PUBLIC_API_URL=$NEXT_PUBLIC_API_URL" > .env.local
echo "==> building the dashboard"
npx next build >"$RUN_DIR/build.log" 2>&1 || { tail -30 "$RUN_DIR/build.log"; exit 1; }
npx next start -p "$WEB_PORT" >"$RUN_DIR/next.log" 2>&1 &
PIDS+=($!)
wait_for "http://127.0.0.1:$WEB_PORT/login" "dashboard" "$RUN_DIR/next.log"

# ── 4 · browser ──────────────────────────────────────────────────────────────
rm -rf "$RUN_DIR/chrome"
"$CHROME" \
  --headless=new --disable-gpu --no-sandbox --hide-scrollbars --lang=ar \
  --remote-debugging-port="$CDP_PORT" --user-data-dir="$RUN_DIR/chrome" \
  about:blank >"$RUN_DIR/chrome.log" 2>&1 &
PIDS+=($!)
wait_for "http://127.0.0.1:$CDP_PORT/json/version" "chrome" "$RUN_DIR/chrome.log"

# ── 5 · capture ──────────────────────────────────────────────────────────────
cd "$REPO_ROOT/frontend"
DASHBOARD_URL="http://127.0.0.1:$WEB_PORT" CDP_URL="http://127.0.0.1:$CDP_PORT" \
  node scripts/capture-screenshots.mjs

echo "==> done"
