/* ╔════════════════════════════════════════════════════════════════════════╗
   ║  GENERATED — `cd frontend && npm run build:icons`. Do not edit.         ║
   ╚════════════════════════════════════════════════════════════════════════╝ */

/*
 * An EXPLICIT registry, not a namespace import.
 *
 * `lucide-react-native` exports ~1777 individual components and no lookup
 * map. `import * as Lucide` then indexing it works, but Metro does not tree-shake a
 * namespace import — so the whole library would ship in the app bundle to render the
 * 90 icons this product actually uses.
 *
 * Generating the list also makes a bad name a COMPILE error instead of a blank space.
 * The old Feather wrapper typed its name as `keyof typeof Feather.glyphMap`, which
 * accepted ~280 names whether a screen used them or not; a typo rendered nothing and
 * read as a deliberate gap. Generating against the INSTALLED package is what caught
 * `home` → `house` and `help-circle` → `circle-question-mark`, two renames that
 * would each have silently erased an icon.
 *
 * Note several keys share a component on purpose: `arrow-forward` and `arrow-right`
 * are both ArrowRight, `notifications` and `bell` are both Bell. The legacy names are
 * kept so ~120 call sites did not have to change in the same commit as the icon set.
 */
import {
  ArrowDownLeft,
  ArrowDownRight,
  ArrowLeft,
  ArrowRight,
  ArrowUpDown,
  ArrowUpLeft,
  ArrowUpRight,
  Award,
  Banknote,
  Bell,
  Book,
  Briefcase,
  Calendar,
  Camera,
  Car,
  Check,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronUp,
  CircleAlert,
  CircleCheck,
  CircleQuestionMark,
  CircleX,
  Clock,
  CloudOff,
  CloudUpload,
  Copy,
  CornerDownLeft,
  CornerUpLeft,
  CreditCard,
  Crosshair,
  DollarSign,
  Download,
  EllipsisVertical,
  ExternalLink,
  Eye,
  EyeOff,
  FileText,
  Flag,
  Funnel,
  Gauge,
  Gift,
  Globe,
  GraduationCap,
  Grid3x3,
  Headphones,
  House,
  Image,
  Inbox,
  Info,
  Key,
  Link,
  LoaderCircle,
  LocateFixed,
  Lock,
  LockOpen,
  LogOut,
  MapPin,
  MessageCircle,
  MessageSquare,
  Minus,
  Navigation,
  Package,
  Pencil,
  Percent,
  Phone,
  PhoneCall,
  Plus,
  Power,
  RefreshCw,
  Search,
  Send,
  Shield,
  SlidersHorizontal,
  Smartphone,
  Sparkles,
  Star,
  Tag,
  Trash2,
  TrendingUp,
  TriangleAlert,
  Truck,
  Upload,
  User,
  Users,
  Wallet,
  WifiOff,
  X,
  Zap,
} from 'lucide-react-native';

export const ICON_REGISTRY = {
  'arrow-down-left': ArrowDownLeft,
  'arrow-down-right': ArrowDownRight,
  'arrow-left': ArrowLeft,
  'arrow-right': ArrowRight,
  'arrow-up-down': ArrowUpDown,
  'arrow-up-left': ArrowUpLeft,
  'arrow-up-right': ArrowUpRight,
  'award': Award,
  'banknote': Banknote,
  'bell': Bell,
  'book': Book,
  'briefcase': Briefcase,
  'calendar': Calendar,
  'camera': Camera,
  'car': Car,
  'check': Check,
  'chevron-down': ChevronDown,
  'chevron-left': ChevronLeft,
  'chevron-right': ChevronRight,
  'chevron-up': ChevronUp,
  'circle-alert': CircleAlert,
  'circle-check': CircleCheck,
  'circle-question-mark': CircleQuestionMark,
  'circle-x': CircleX,
  'clock': Clock,
  'cloud-off': CloudOff,
  'cloud-upload': CloudUpload,
  'copy': Copy,
  'corner-down-left': CornerDownLeft,
  'corner-up-left': CornerUpLeft,
  'credit-card': CreditCard,
  'crosshair': Crosshair,
  'dollar-sign': DollarSign,
  'download': Download,
  'ellipsis-vertical': EllipsisVertical,
  'external-link': ExternalLink,
  'eye': Eye,
  'eye-off': EyeOff,
  'file-text': FileText,
  'flag': Flag,
  'funnel': Funnel,
  'gauge': Gauge,
  'gift': Gift,
  'globe': Globe,
  'graduation-cap': GraduationCap,
  'grid-3x3': Grid3x3,
  'headphones': Headphones,
  'house': House,
  'image': Image,
  'inbox': Inbox,
  'info': Info,
  'key': Key,
  'link': Link,
  'loader-circle': LoaderCircle,
  'locate-fixed': LocateFixed,
  'lock': Lock,
  'lock-open': LockOpen,
  'log-out': LogOut,
  'map-pin': MapPin,
  'message-circle': MessageCircle,
  'message-square': MessageSquare,
  'minus': Minus,
  'navigation': Navigation,
  'package': Package,
  'pencil': Pencil,
  'percent': Percent,
  'phone': Phone,
  'phone-call': PhoneCall,
  'plus': Plus,
  'power': Power,
  'refresh-cw': RefreshCw,
  'search': Search,
  'send': Send,
  'shield': Shield,
  'sliders-horizontal': SlidersHorizontal,
  'smartphone': Smartphone,
  'sparkles': Sparkles,
  'star': Star,
  'tag': Tag,
  'trash-2': Trash2,
  'trending-up': TrendingUp,
  'triangle-alert': TriangleAlert,
  'truck': Truck,
  'upload': Upload,
  'user': User,
  'users': Users,
  'wallet': Wallet,
  'wifi-off': WifiOff,
  'x': X,
  'zap': Zap,
} as const;

/** Every icon name this product may use. A typo is a type error. */
export type IconName = keyof typeof ICON_REGISTRY;
