/** API + platform-wide constants. */

export const API_VERSION = 'v1';

export const ENDPOINTS = {
  ping: '/ping',
  config: '/config',
  zones: '/zones',
  auth: {
    register: '/auth/register',
    verifyOtp: '/auth/verify-otp',
    requestOtp: '/auth/request-otp',
    resendOtp: '/auth/resend-otp',
    login: '/auth/login',
    verifyMfa: '/auth/mfa/verify',
    mfaSetup: '/auth/mfa/setup',
    mfaConfirm: '/auth/mfa/confirm',
    mfaDisable: '/auth/mfa/disable',
    forgotPassword: '/auth/forgot-password',
    resetPassword: '/auth/reset-password',
    me: '/auth/me',
    logout: '/auth/logout',
    logoutAll: '/auth/logout-all',
  },
  profile: {
    base: '/profile',
    changePassword: '/profile/change-password',
    requestPhone: '/profile/phone/request',
    confirmPhone: '/profile/phone/confirm',
  },
  student: {
    profile: '/student/profile',
    addresses: '/student/addresses',
    address: (id: string) => `/student/addresses/${id}`,
    addressDefault: (id: string) => `/student/addresses/${id}/default`,
  },
  chat: {
    conversations: '/chat/conversations',
    open: (tripId: string) => `/chat/trips/${tripId}/open`,
    messages: (conversationId: string) => `/chat/conversations/${conversationId}/messages`,
    send: (conversationId: string) => `/chat/conversations/${conversationId}/messages`,
    read: (conversationId: string) => `/chat/conversations/${conversationId}/read`,
  },
  universities: {
    list: '/universities',
    one: (id: string) => `/universities/${id}`,
  },
  routes: {
    list: '/routes',
    one: (id: string) => `/routes/${id}`,
  },
  transport: {
    plans: '/plans',
    subscriptions: '/subscriptions',
    cancelSubscription: (id: string) => `/subscriptions/${id}/cancel`,
    availableTrips: '/trips/available',
    myTrips: '/trips/mine',
    bookTrip: (tripId: string) => `/trips/${tripId}/book`,
    tripLocation: (tripId: string) => `/trips/${tripId}/location`,
    cancelBooking: (passengerId: string) => `/trips/passengers/${passengerId}/cancel`,
  },
  driverTrips: {
    list: '/driver/trips',
    show: (id: string) => `/driver/trips/${id}`,
    passengers: (id: string) => `/driver/trips/${id}/passengers`,
    start: (id: string) => `/driver/trips/${id}/start`,
    end: (id: string) => `/driver/trips/${id}/end`,
    cancel: (id: string) => `/driver/trips/${id}/cancel`,
    board: (id: string) => `/driver/trips/${id}/board`,
    dropoff: (id: string) => `/driver/trips/${id}/dropoff`,
    location: (id: string) => `/driver/trips/${id}/location`,
  },
  driver: {
    profile: '/driver/profile',
    documents: '/driver/documents',
    submit: '/driver/submit',
    vehicles: '/driver/vehicles',
    performance: '/driver/performance',
    withdrawals: '/driver/wallet/withdrawals',
  },
  adminWithdrawals: {
    list: '/admin/withdrawals',
    approve: (id: string) => `/admin/withdrawals/${id}/approve`,
    reject: (id: string) => `/admin/withdrawals/${id}/reject`,
  },
  driverOffers: {
    list: '/driver/trips/offers',
    accept: (tripId: string) => `/driver/trips/offers/${tripId}/accept`,
  },
  wallet: {
    show: '/wallet',
    transactions: '/wallet/transactions',
    topupInstructions: '/wallet/topup-instructions',
  },
  payments: {
    list: '/payments',
    create: '/payments',
    one: (id: string) => `/payments/${id}`,
    instructions: (id: string) => `/payments/${id}/instructions`,
    proof: (id: string) => `/payments/${id}/proof`,
    adminQueue: '/admin/payments',
    adminOne: (id: string) => `/admin/payments/${id}`,
    adminProof: (paymentId: string) => `/admin/payments/proof/${paymentId}`,
    adminApprove: (id: string) => `/admin/payments/${id}/approve`,
    adminReject: (id: string) => `/admin/payments/${id}/reject`,
  },
  notifications: {
    list: '/notifications',
    unreadCount: '/notifications/unread-count',
    readAll: '/notifications/read-all',
    read: (id: string) => `/notifications/${id}/read`,
    preferences: '/notifications/preferences',
    devices: '/notifications/devices',
  },
  ratings: {
    mine: '/ratings/mine',
    received: '/ratings/received',
    rate: (tripId: string) => `/trips/${tripId}/ratings`,
  },
  support: {
    list: '/support/tickets',
    create: '/support/tickets',
    one: (id: string) => `/support/tickets/${id}`,
    reply: (id: string) => `/support/tickets/${id}/reply`,
    adminList: '/admin/support/tickets',
    adminEscalate: (id: string) => `/admin/support/tickets/${id}/escalate`,
    adminStatus: (id: string) => `/admin/support/tickets/${id}/status`,
  },
  complaints: {
    mine: '/complaints',
    file: '/complaints',
    adminList: '/admin/complaints',
    adminOne: (id: string) => `/admin/complaints/${id}`,
    adminStatus: (id: string) => `/admin/complaints/${id}/status`,
  },
  parcels: {
    mine: '/parcels',
    create: '/parcels',
    one: (id: string) => `/parcels/${id}`,
    cancel: (id: string) => `/parcels/${id}/cancel`,
    courierAvailable: '/courier/parcels/available',
    courierAccept: (id: string) => `/courier/parcels/${id}/accept`,
    courierPickup: (id: string) => `/courier/parcels/${id}/pickup`,
    courierDeliver: (id: string) => `/courier/parcels/${id}/deliver`,
  },
  rewards: {
    show: '/rewards',
    transactions: '/rewards/transactions',
    redeem: '/rewards/redeem',
  },
  lostFound: {
    list: '/lost-found',
    mine: '/lost-found/mine',
    report: '/lost-found',
    candidates: (id: string) => `/lost-found/${id}/candidates`,
    resolve: (id: string) => `/lost-found/${id}/resolve`,
  },
  exchange: {
    list: '/exchange',
    mine: '/exchange/mine',
    create: '/exchange',
    reserve: (id: string) => `/exchange/${id}/reserve`,
    close: (id: string) => `/exchange/${id}/close`,
  },
  rideRequests: {
    create: '/ride-requests',
    estimate: '/ride-requests/estimate',
    mine: '/ride-requests/mine',
    cancel: (id: string) => `/ride-requests/${id}/cancel`,
  },
  assistant: {
    conversations: '/assistant/conversations',
    messages: (id: string) => `/assistant/conversations/${id}`,
    send: '/assistant/send',
    adminInsights: '/admin/ai/insights',
    adminRisks: '/admin/ai/risks',
    adminRisk: (userId: string) => `/admin/ai/risks/${userId}`,
  },
  sos: {
    trigger: '/sos',
    mine: '/sos/mine',
  },
  emergencyContacts: {
    list: '/emergency-contacts',
    create: '/emergency-contacts',
    one: (id: string) => `/emergency-contacts/${id}`,
  },
  admin: {
    users: '/admin/users',
    drivers: '/admin/drivers',
    driver: (id: string) => `/admin/drivers/${id}`,
    reviewDriver: (id: string) => `/admin/drivers/${id}/review`,
    reviewDocument: (docId: string) => `/admin/drivers/documents/${docId}/review`,
    documentFile: (docId: string) => `/admin/drivers/documents/${docId}/file`,
    universities: '/admin/universities',
    university: (id: string) => `/admin/universities/${id}`,
    rideRequests: '/admin/ride-requests',
    matchingRun: '/admin/matching/run',
    walletCredit: '/admin/wallets/credit',
    reportsFinancial: '/admin/reports/financial',
    zones: '/admin/zones',
    zone: (id: string) => `/admin/zones/${id}`,
    disputes: '/admin/disputes',
    dispute: (id: string) => `/admin/disputes/${id}`,
    disputeInvestigate: '/admin/disputes/investigate',
    disputeAssign: (id: string) => `/admin/disputes/${id}/assign`,
    disputeResolve: (id: string) => `/admin/disputes/${id}/resolve`,
    disputeDismiss: (id: string) => `/admin/disputes/${id}/dismiss`,
    disputeFreeze: (id: string) => `/admin/disputes/${id}/freeze`,
    disputeUnfreeze: (id: string) => `/admin/disputes/${id}/unfreeze`,
  },
} as const;

export const OTP_LENGTH = 6;
export const REWARD_TIERS = ['bronze', 'silver', 'gold', 'platinum'] as const;
